# Sources
#CardImages path

IMAGE_PATH = "./CardImages/"
IMAGE_FORMAT = ".gif"
RESIZE_RATIO = 0.6
CHOSEN_RESIZE_RATIO = 0.4
BACKGROUND_IMAGE_PATH = './CardImages/background.gif'

#DECK 
COLOR_LIST = ['blue','green','red','yellow']
FILL_LIST = ['clear','shaded','solid' ]
SHAPE_LIST = ['circle','square', 'triangle']
NUM_LIST = ['1','2','3']

#UI
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
GAME_NAME = "SET GAME"

#DESK
DESK_WIDTH = 400
DESK_HEIGHT = 300

DESK_CARDS_ONEROW = 4
DESK_CARDS_ONECOL = 5
DESK_CARDS_CAPACITY = DESK_CARDS_ONEROW*DESK_CARDS_ONECOL

#BUTTON
BUTTON_WIDTH = 100
BUTTON_HEIGHT = 80
#card button
CHOSEN_THICKNESS = 0
NORMAL_THICKNESS = 0
#submit button
SUBMIt_BUTTON_GRIDROW = 6
SUBMIT_BuTTON_GRIDCOL = 3

#Game attributes
EASY = "easy"
MIDDLE = "middle"
HARD = "hard"
DIFFICULTY = EASY
MAX_SUBMIT_CARDS_NUM = 3

#CLOCK
CLOCK_ROW = 0
CLOCK_COL = 4

#restart button
RESTART_ROW = 0
RESTART_COL = 0